### ISSUE TITLE
Criar biblioteca de referências no Zotero

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/artigo-ensino-de-biologia#4]
- [x] Criar uma coleção específica com as referências que serão utilizadas no artigo - @yacifarias
- [x] Convidar @ericbrasiln para a biblioteca
- [x] Documentar - @yacifarias

**Comment by yacifarias** [comment]
Criei a biblio. Agora, será que alguns artigos que coloquei para usarmos de referência não vai aparecer na raspagem?? Teria problema?

**Comment by ericbrasiln** [comment]
Não vejo problema, pois são etapas distintas da reflexão.

**Comment by ericbrasiln** [comment]
[Link para a biblioteca no Zotero](https://www.zotero.org/groups/4789788/artigo_ensino_de_biologia_e_eao/library)
