### ISSUE TITLE
Levantamento Bibliográfico

### ISSUE THREAD

**Issue by ericbrasiln** [ericbrasiln/artigo-ensino-de-biologia#5]
Realizar levantamento bibliográfico sobre o tema:

- [x] Criar lista de termos para busca
- [x] Buscar no Google Scholar
- [ ] Buscar no Scopus
- [ ] Buscar no Web of Science

**Comment by yacifarias** [comment]
Usei os termos "ensino de biologia crítico"; "ensino de biologia antirracista"; "ensino de biologia e gênero"

**Comment by ericbrasiln** [comment]
A busca foi feita com os termos sem as aspas duplas (sem busca por expressão exata).

- Busca 1: `ensino de biologia crítico`
- Busca 2: `ensino de biologia antirracista`
- Busca 3: `ensino de biologia antirracista`

Não foi realizada uma busca exaustiva, mas sim um levantamento geral das temáticas.

Inicialmente esse levantamento foi realizado apenas no google Scholar.
